tierra_topicsolved_controller_mark:
    path: /topicsolved/mark/{solve}/{forum_id}/{post_id}
    defaults: { _controller: tierra.topicsolved.controller:mark }
    requirements:
        solve: solved|unsolved
        forum_id: \d+
        post_id: \d+