services:
    tierra.topicsolved.controller:
        class: tierra\topicsolved\controller\main_controller
        arguments:
            - @tierra.topicsolved.topicsolved
            - @config
            - @controller.helper
            - @request
            - @template
            - %core.root_path%
            - %core.php_ext%
    tierra.topicsolved.event:
        class: tierra\topicsolved\event\main_listener
        arguments:
            - @tierra.topicsolved.topicsolved
            - @controller.helper
            - @template
            - @user
            - @auth
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }
    tierra.topicsolved.event.acp_forums:
        class: tierra\topicsolved\event\acp_forums
        arguments:
            - @tierra.topicsolved.topicsolved
            - @template
        tags:
            - { name: event.listener }
    tierra.topicsolved.topicsolved:
        class: tierra\topicsolved\topicsolved
        arguments:
            - @dbal.conn
            - @user
            - @auth